name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t my-node-app:new .

    - name: Tagging Docker image
      run: docker tag my-node-app:new sanushgowda7/my-node-app:new

    - name: Push Docker image to Docker Hub
      run: docker push sanushgowda7/my-node-app:new